--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vktest-deployment
  namespace: development
  labels:
    app: vktest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vktest
  template:
    metadata:
      labels:
        app: vktest
    spec:
      containers:
      - name: vktest-container
        image: datawire/quote:0.5.0
        ports:
        - containerPort: 8080
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
